import type { FeedRequestCard, WorkspaceSnapshot } from "@/lib/supabase/types";

const now = Date.now();

export const previewFeed: FeedRequestCard[] = [
  {
    id: "8af9710e-0cb1-419a-85ce-a90dc5fcdf20",
    lane: "social",
    title: "Jazz rooftop set and a quiet after-walk",
    description: "Looking for a calm plus-one who likes live music and clear plans. Public venue, short chat before we commit.",
    areaLabel: null,
    meetupAt: null,
    createdAt: new Date(now - 1000 * 60 * 12).toISOString(),
    verifiedOnly: true,
    hostDisplayName: null,
    hostVerified: true,
    tags: ["music", "public-space", "easygoing"],
  },
  {
    id: "71864dc5-c8ed-4055-a6a3-261636344e2d",
    lane: "errand",
    title: "Hospital follow-up and pharmacy stop",
    description: "Need practical company for a short visit and pickup. Prefer someone punctual and comfortable with low-key support.",
    areaLabel: null,
    meetupAt: null,
    createdAt: new Date(now - 1000 * 60 * 33).toISOString(),
    verifiedOnly: true,
    hostDisplayName: null,
    hostVerified: true,
    tags: ["hospital", "support", "structured"],
  },
  {
    id: "b9863146-1318-4c36-aeb0-2f4b7f68f5de",
    lane: "social",
    title: "Museum afternoon with coffee and photo break",
    description: "I want company, not chaos. Planning a clean route, fixed timing, and a public meetup point.",
    areaLabel: null,
    meetupAt: null,
    createdAt: new Date(now - 1000 * 60 * 46).toISOString(),
    verifiedOnly: false,
    hostDisplayName: null,
    hostVerified: true,
    tags: ["museum", "coffee", "public-space"],
  },
];

export const emptyWorkspaceSnapshot: WorkspaceSnapshot = {
  profile: {
    id: "00000000-0000-0000-0000-000000000000",
    displayName: "Member",
    aboutMe: "",
    homeArea: "",
    role: "member",
  },
  myRequests: [],
  incomingJoinRequests: [],
  activeSession: null,
};

export const previewWorkspace: WorkspaceSnapshot = {
  profile: {
    id: "93530cd9-3b23-4827-b04a-b810a7abfa8d",
    displayName: "Preview Member",
    aboutMe: "Prefers clear plans, public spaces, and fast confirmations.",
    homeArea: "Lower Parel",
    role: "member",
  },
  myRequests: [
    {
      id: "0e6ae108-0c8b-4740-b931-dba69f96455c",
      lane: "social",
      title: "Gallery opening with a short dinner after",
      areaLabel: "Fort",
      meetupAt: new Date(now + 1000 * 60 * 150).toISOString(),
      status: "open",
      verifiedOnly: true,
      pendingJoinCount: 2,
      partnerDisplayName: null,
      partnerId: null,
      createdAt: new Date(now - 1000 * 60 * 20).toISOString(),
      lastActivityAt: new Date(now - 1000 * 60 * 5).toISOString(),
      completedAt: null,
      userOutcome: null,
      userMeetAgain: null,
    },
    {
      id: "d9fd0d36-e844-4133-a0a1-74488992ae98",
      lane: "errand",
      title: "Passport office morning run",
      areaLabel: "BKC",
      meetupAt: new Date(now + 1000 * 60 * 60 * 18).toISOString(),
      status: "matched",
      verifiedOnly: true,
      pendingJoinCount: 0,
      partnerDisplayName: "Aarav",
      partnerId: "622ab563-a5b4-4582-8520-be62663382ed",
      createdAt: new Date(now - 1000 * 60 * 60 * 2).toISOString(),
      lastActivityAt: new Date(now - 1000 * 60 * 3).toISOString(),
      completedAt: null,
      userOutcome: null,
      userMeetAgain: null,
    },
  ],
  incomingJoinRequests: [
    {
      id: "29676f2f-56d8-47da-a196-a45fd6f405c2",
      requestId: "0e6ae108-0c8b-4740-b931-dba69f96455c",
      requestTitle: "Gallery opening with a short dinner after",
      requestLane: "social",
      joinerId: "7821aeb3-9b09-4bd0-8e59-6ff9541fa5c7",
      joinerDisplayName: "Mira",
      joinerAboutMe: "Comfortable with structured plans and public meetups. Usually early.",
      introMessage: "I like calm events and can reach the gallery 10 minutes early.",
      createdAt: new Date(now - 1000 * 60 * 11).toISOString(),
    },
  ],
  activeSession: {
    requestId: "d9fd0d36-e844-4133-a0a1-74488992ae98",
    requestTitle: "Passport office morning run",
    lane: "errand",
    areaLabel: "BKC",
    meetupAt: new Date(now + 1000 * 60 * 60 * 18).toISOString(),
    checkInEnabled: true,
    partnerDisplayName: "Aarav",
    partnerId: "622ab563-a5b4-4582-8520-be62663382ed",
    messages: [
      {
        id: 1,
        requestId: "d9fd0d36-e844-4133-a0a1-74488992ae98",
        senderType: "system",
        senderId: null,
        senderName: "Tag Along",
        body: "Match confirmed. Use this room to align your exact meeting point, ETA, and safety check-in plan.",
        createdAt: new Date(now - 1000 * 60 * 8).toISOString(),
      },
      {
        id: 2,
        requestId: "d9fd0d36-e844-4133-a0a1-74488992ae98",
        senderType: "user",
        senderId: "622ab563-a5b4-4582-8520-be62663382ed",
        senderName: "Aarav",
        body: "I can meet you outside gate 2 at 9:15. Want to share a backup number?",
        createdAt: new Date(now - 1000 * 60 * 3).toISOString(),
      },
    ],
  },
};
